title: Switch2OSM
description: >
  Switch to OpenStreetMap and discover how you can build beautiful maps from the world’s best map data.
baseurl: "" # the subpath of your site, e.g. /blog
copyright: 2013–2020 OpenStreetMap and contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA</a>
url: ""
github_username: switch2osm

# Build settings
markdown: kramdown

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

menu:
  - title: Why Switch?
    url: /why-switch/
  - title: Case Studies
    url: /case-studies/
  - title: The Basics
    url: /the-basics/
  - title: Using Tiles
    url: /using-tiles/
  - title: Serving Tiles
    url: /serving-tiles/
  - title: Other Uses
    url: /other-uses/
  - title: Providers
    url: /providers/
  - title: Find Out More
    url: /find-out-more/
