site_name: Switch2OSM
site_url: https://switch2osm.org/
repo_url: https://github.com/switch2osm/switch2osm
repo_name: switch2osm/switch2osm
edit_uri: edit/main/docs/
dev_addr: 127.0.0.1:8080
copyright: © 2013–2025 OpenStreetMap and contributors, <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/2.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">Creative Commons Attribution-ShareAlike 2.0 Generic License</a>.
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: assets/favicon.png
  icon:
    logo: simple/openstreetmap
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: lime
      scheme: default
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy
    - announce.dismiss
extra:
  social:
    - icon: material/translate
      link: https://github.com/switch2osm/switch2osm/#translation
    - icon: fontawesome/solid/globe
      link: https://openstreetmap.org/
    - icon: fontawesome/brands/discourse
      link: https://community.openstreetmap.org/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/openstreetmap
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OpenStreetMap/
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: ⚓︎
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: none
  # Python Markdown Extensions
  - pymdownx.blocks.html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Why: why-switch.md
  - Cases: case-studies.md
  - Basics: the-basics.md
  - Using:
      # - Own tiles: using-tiles/index.md
      - using-tiles/index.md
      - Leaflet: using-tiles/getting-started-with-leaflet.md
      - OpenLayers: using-tiles/getting-started-with-openlayers.md
      - MapLibre: using-tiles/getting-started-with-maplibre.md
  - Serving:
      # - Serving tiles: serving-tiles/index.md
      - serving-tiles/index.md
      - Manually:
          - Debian 13: serving-tiles/manually-building-a-tile-server-debian-13.md
          - Debian 12: serving-tiles/manually-building-a-tile-server-debian-12.md
          - Debian 11: serving-tiles/manually-building-a-tile-server-debian-11.md
          - Ubuntu 24.04: serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md
          - Ubuntu 22.04: serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
          - Ubuntu 20.04: serving-tiles/manually-building-a-tile-server-ubuntu-20-04-lts.md
          - Ubuntu 18.04: serving-tiles/manually-building-a-tile-server-ubuntu-18-04-lts.md
      - Docker: serving-tiles/using-a-docker-container.md
      - Munin: serving-tiles/monitoring-using-munin.md
      - Updating:
          - osm2pgsql: serving-tiles/updating-as-people-edit-osm2pgsql-replication.md
          - pyosmium: serving-tiles/updating-as-people-edit-pyosmium.md
          - osmosis: serving-tiles/updating-as-people-edit-osmosis.md
  - Other: other-uses.md
  - Providers: providers.md
  - More: find-out-more.md
plugins:
  - search:
      lang: [en, uk, zh-TW]
  - macros
  - ezlinks
  - glightbox
  - section-index
  - privacy
  # This part is for organising languages in specific folders
  # Using a folder per language structure
  # https://ultrabug.github.io/mkdocs-static-i18n/
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - # ISO code of your language
          locale: en
          # Name of your languge
          name: English
          default: true
          # Day/Night toggle
          theme:
            palette:
              - toggle:
                  name: Switch to light mode
              - toggle:
                  name: Switch to dark mode
              - toggle:
                  name: Switch to system preference
          # Translate copyright statement
          copyright: © 2013–2025 OpenStreetMap and contributors, <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/2.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">Creative Commons Attribution-ShareAlike 2.0 Generic License</a>.
          nav_translations:
            # Menu item name for the /index.md
            Home: Switch2OSM
            # Menu item name for the /why-switch.md
            Why: Why Switch?
            # Menu item name for the /case-studies.md
            Cases: Case Studies
            # Menu item name for the /the-basics.md
            Basics: The Basics
            # Menu item name for the "Using Tiles" tab
            Using: Using Tiles
            # Menu item name for the side menu
            Leaflet: Getting started with Leaflet
            # Menu item name for the side menu
            OpenLayers: Getting started with OpenLayers
            # Menu item name for the side menu
            MapLibre: Getting started with MapLibre GL
            # Menu item name for the side menu
            Vector Tiles: Power of Vector Map Tiles
            # Menu item name for the "Serving Tiles" tab
            Serving: Serving Tiles
            # Serving tiles: Manually building a tile server
            Manually: Manually building a tile server
            # Serving tiles: Using a Docker container
            Docker: Using a Docker container
            # Serving tiles: Monitoring using Munin
            Munin: Monitoring using Munin
            # Serving tiles: Updating your database as people edit OpenStreetMap
            Updating: Updating your database as people edit OpenStreetMap
            # Menu item name for the /other-uses.md
            Other: Other Uses
            # Menu item name for the /providers.md
            Providers: Providers
            # Menu item name for the /find-out-more.md
            More: Find Out More
        - locale: uk
          name: Українська
          theme:
            palette:
              - toggle:
                  name: Увімкнути світлий режим
              - toggle:
                  name: Увімкнути темний режим
              - toggle:
                  name: Увімкнути режим системи
          copyright: "© 2013–2025 Учасники OpenStreetMap, <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/2.0/deed.uk\" target=\"_blank\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/2.0/80x15.png\" /></a><br />Матеріали цього сайту ліцензуються на умовах Ліцензії – <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/2.0/deed.uk\" target=\"_blank\">Creative Commons Attribution-ShareAlike 2.0 Generic License</a>."
          nav_translations:
            Home: Switch2OSM
            Why: "Навіщо?"
            Cases: Вже з OSM
            Basics: Основи
            Using: Мапа
            Leaflet: За допомогою Leaflet
            OpenLayers: За допомогою OpenLayers
            MapLibre: Початок роботи з MapLibre GL
            Vector Tiles: Переваги векторних тайлів
            Serving: Власний сервер
            Manually: Розгортаємо сервер вручну
            Docker: Використання контейнера Docker
            Munin: Моніторинг за допомогою Munin
            Updating: Оновлення бази даних правками з OpenStreetMap
            Serving vector tiles: Векторні тайли
            Steps: Загальні кроки
            TileServer GL: Розгортання TileServer GL
            Other: Інше
            Providers: Постачальники
            More: Отримання допомоги
        - locale: zh-TW
          name: 台灣華語
          theme:
            palette:
              - toggle:
                  name: 切換到燈光模式
              - toggle:
                  name: 切換到深色模式
              - toggle:
                  name: 切換到系統偏好設定
          copyright: "© 2013–2025 開放街圖與貢獻者。 <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/2.0/\" target=\"_blank\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/2.0/80x15.png\" /></a><br />這些資料採用 <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/2.0/\" target=\"_blank\">創用CC相同方式分享 2.0 未本地化授權條款</a>。"
          nav_translations:
            Home: Switch2OSM
            Why: 為什麼更換？
            Cases: 案例分析
            Basics: 基本資訊
            Using: 使用圖磚
            Leaflet: 開始使用 Leaflet
            OpenLayers: 開始使用 OpenLayers
            Vector Tiles: 向量地圖圖磚的威力
            Serving: 供給圖磚
            Manually: 手動建構圖磚伺服器
            Docker: 使用 Docker 容器
            Munin: 採用 Munin 監控
            Updating: 在人們編輯過開放街圖之後更新資料庫
            Serving vector tiles: 向量地圖圖磚
            Steps: 一般步驟
            TileServer GL: 開始使用 TileServer GL
            Other: 其他用途
            Providers: 提供者
            More: 取得協助
        - locale: "null"
          fixed_link: https://github.com/switch2osm/switch2osm/#translation
          name: Help to translate
